@echo off
echo zapusk venva...
python -m venv venv
echo venv activating...
call venv\Scripts\activate
echo ustanovka zavisimostey...
pip install pyautogui pywhatkit pandas openpyxl
echo Готово!
pause
